# Generated by Django 4.0.4 on 2022-04-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_patientinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='expertise',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], null=True),
        ),
    ]
