# Generated by Django 4.0.4 on 2022-05-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_disease_metric_usermetrics_user_disease'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMetrics',
            new_name='UserMetric',
        ),
    ]
