# Generated by Django 4.0.4 on 2022-05-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_usermetrics_usermetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetric',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
