# Generated by Django 4.0.4 on 2022-05-14 12:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_usermetric_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('value', models.TextField()),
                ('type', models.IntegerField(blank=True, choices=[(1, 'Number'), (2, 'String')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, unique=True)),
                ('is_disease', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDoctorLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
                ('upper_limit', models.FloatField()),
                ('lower_limit', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='metric',
            name='lower_limit',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='lower_warning',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='upper_limit',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='upper_warning',
        ),
        migrations.RemoveField(
            model_name='user',
            name='disease',
        ),
        migrations.AddField(
            model_name='metric',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='metrics',
            field=models.ManyToManyField(blank=True, null=True, through='api.UserDoctorLimits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.AddField(
            model_name='userdoctorlimits',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_limits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdoctorlimits',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_limits', to='api.metric'),
        ),
        migrations.AddField(
            model_name='userdoctorlimits',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_limits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notes',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notes',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
