# Generated by Django 4.0.4 on 2022-05-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_user_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='drinking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='exercising',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='smoking',
            field=models.BooleanField(default=False),
        ),
    ]
