# Generated by Django 4.0.4 on 2022-05-14 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_notes_note_rename_quotes_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetric',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
