# Generated by Django 4.0.4 on 2022-05-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_usermetric_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermetric',
            old_name='date',
            new_name='datetime',
        ),
    ]
