# Generated by Django 4.0.4 on 2022-05-14 16:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_date_usermetric_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermetric',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='usermetric',
            name='user',
        ),
        migrations.AlterField(
            model_name='usermetric',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_metric', to='api.metric'),
        ),
        migrations.CreateModel(
            name='UserMetricsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usermetric',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_metric', to='api.usermetricsgroup'),
        ),
    ]
