# Generated by Django 4.0.4 on 2022-05-15 17:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_note_doctor_alter_note_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
                ('upper_limit', models.FloatField()),
                ('lower_limit', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='metrics',
        ),
        migrations.AddField(
            model_name='user',
            name='limits',
            field=models.ManyToManyField(through='api.Limits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserDoctorLimits',
        ),
        migrations.AddField(
            model_name='limits',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_limits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='limits',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='api.metric'),
        ),
        migrations.AddField(
            model_name='limits',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_limits', to=settings.AUTH_USER_MODEL),
        ),
    ]
