# Generated by Django 4.0.4 on 2022-05-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_limits_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limit',
            name='value',
        ),
    ]
