# Generated by Django 4.0.4 on 2022-05-15 18:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_limit_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='limit',
            name='date',
        ),
        migrations.RemoveField(
            model_name='limit',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='limit',
            name='patient',
        ),
        migrations.AlterField(
            model_name='user',
            name='limits',
            field=models.ManyToManyField(through='api.LimitsGroup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='limitsgroup',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_limits_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='limitsgroup',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_limits_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='limit',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='api.limitsgroup'),
            preserve_default=False,
        ),
    ]
