# Generated by Django 4.0.4 on 2022-05-15 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_limitsgroup_remove_limit_date_remove_limit_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetric',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='api.usermetricsgroup'),
            preserve_default=False,
        ),
    ]
