# Generated by Django 4.0.4 on 2022-05-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_usermetric_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='limit',
            unique_together={('group', 'metric')},
        ),
    ]
