# Generated by Django 4.0.4 on 2022-05-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_limit_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='limitsgroup',
            unique_together={('doctor', 'patient')},
        ),
    ]
