# Generated by Django 4.0.4 on 2022-05-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_limitsgroup_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitsgroup',
            name='receive_notification',
            field=models.BooleanField(default=False),
        ),
    ]
